<?php
/**
 * ComparisonSummaryModel
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * ComparisonSummaryModel Class Doc Comment
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ComparisonSummaryModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ComparisonSummaryModel';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'accuracy' => 'float',
        'by_label' => 'array<string,string>',
        'correct_fields' => 'string[]',
        'counts' => '\Gemina\Sdk\Model\CountBreakdownModel',
        'coverage' => 'float',
        'differences' => '\Gemina\Sdk\Model\FieldDifferenceModel[]',
        'exact_match' => 'bool',
        'extra_fields' => 'string[]',
        'f1' => 'float',
        'incorrect_fields' => 'string[]',
        'missing_fields' => 'string[]',
        'precision' => 'float',
        'recall' => 'float',
        'strict_f1' => 'float',
        'strict_precision' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'accuracy' => null,
        'by_label' => null,
        'correct_fields' => null,
        'counts' => null,
        'coverage' => null,
        'differences' => null,
        'exact_match' => null,
        'extra_fields' => null,
        'f1' => null,
        'incorrect_fields' => null,
        'missing_fields' => null,
        'precision' => null,
        'recall' => null,
        'strict_f1' => null,
        'strict_precision' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'accuracy' => false,
        'by_label' => false,
        'correct_fields' => false,
        'counts' => false,
        'coverage' => false,
        'differences' => false,
        'exact_match' => false,
        'extra_fields' => false,
        'f1' => false,
        'incorrect_fields' => false,
        'missing_fields' => false,
        'precision' => false,
        'recall' => false,
        'strict_f1' => true,
        'strict_precision' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accuracy' => 'accuracy',
        'by_label' => 'by_label',
        'correct_fields' => 'correct_fields',
        'counts' => 'counts',
        'coverage' => 'coverage',
        'differences' => 'differences',
        'exact_match' => 'exact_match',
        'extra_fields' => 'extra_fields',
        'f1' => 'f1',
        'incorrect_fields' => 'incorrect_fields',
        'missing_fields' => 'missing_fields',
        'precision' => 'precision',
        'recall' => 'recall',
        'strict_f1' => 'strict_f1',
        'strict_precision' => 'strict_precision'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accuracy' => 'setAccuracy',
        'by_label' => 'setByLabel',
        'correct_fields' => 'setCorrectFields',
        'counts' => 'setCounts',
        'coverage' => 'setCoverage',
        'differences' => 'setDifferences',
        'exact_match' => 'setExactMatch',
        'extra_fields' => 'setExtraFields',
        'f1' => 'setF1',
        'incorrect_fields' => 'setIncorrectFields',
        'missing_fields' => 'setMissingFields',
        'precision' => 'setPrecision',
        'recall' => 'setRecall',
        'strict_f1' => 'setStrictF1',
        'strict_precision' => 'setStrictPrecision'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accuracy' => 'getAccuracy',
        'by_label' => 'getByLabel',
        'correct_fields' => 'getCorrectFields',
        'counts' => 'getCounts',
        'coverage' => 'getCoverage',
        'differences' => 'getDifferences',
        'exact_match' => 'getExactMatch',
        'extra_fields' => 'getExtraFields',
        'f1' => 'getF1',
        'incorrect_fields' => 'getIncorrectFields',
        'missing_fields' => 'getMissingFields',
        'precision' => 'getPrecision',
        'recall' => 'getRecall',
        'strict_f1' => 'getStrictF1',
        'strict_precision' => 'getStrictPrecision'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('accuracy', $data ?? [], null);
        $this->setIfExists('by_label', $data ?? [], null);
        $this->setIfExists('correct_fields', $data ?? [], null);
        $this->setIfExists('counts', $data ?? [], null);
        $this->setIfExists('coverage', $data ?? [], null);
        $this->setIfExists('differences', $data ?? [], null);
        $this->setIfExists('exact_match', $data ?? [], null);
        $this->setIfExists('extra_fields', $data ?? [], null);
        $this->setIfExists('f1', $data ?? [], null);
        $this->setIfExists('incorrect_fields', $data ?? [], null);
        $this->setIfExists('missing_fields', $data ?? [], null);
        $this->setIfExists('precision', $data ?? [], null);
        $this->setIfExists('recall', $data ?? [], null);
        $this->setIfExists('strict_f1', $data ?? [], null);
        $this->setIfExists('strict_precision', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['accuracy'] === null) {
            $invalidProperties[] = "'accuracy' can't be null";
        }
        if ($this->container['correct_fields'] === null) {
            $invalidProperties[] = "'correct_fields' can't be null";
        }
        if ($this->container['counts'] === null) {
            $invalidProperties[] = "'counts' can't be null";
        }
        if ($this->container['coverage'] === null) {
            $invalidProperties[] = "'coverage' can't be null";
        }
        if ($this->container['differences'] === null) {
            $invalidProperties[] = "'differences' can't be null";
        }
        if ($this->container['exact_match'] === null) {
            $invalidProperties[] = "'exact_match' can't be null";
        }
        if ($this->container['extra_fields'] === null) {
            $invalidProperties[] = "'extra_fields' can't be null";
        }
        if ($this->container['f1'] === null) {
            $invalidProperties[] = "'f1' can't be null";
        }
        if ($this->container['incorrect_fields'] === null) {
            $invalidProperties[] = "'incorrect_fields' can't be null";
        }
        if ($this->container['missing_fields'] === null) {
            $invalidProperties[] = "'missing_fields' can't be null";
        }
        if ($this->container['precision'] === null) {
            $invalidProperties[] = "'precision' can't be null";
        }
        if ($this->container['recall'] === null) {
            $invalidProperties[] = "'recall' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accuracy
     *
     * @return float
     */
    public function getAccuracy()
    {
        return $this->container['accuracy'];
    }

    /**
     * Sets accuracy
     *
     * @param float $accuracy tp / total_expected — 'correct out of all expected'
     *
     * @return self
     */
    public function setAccuracy($accuracy)
    {
        if (is_null($accuracy)) {
            throw new \InvalidArgumentException('non-nullable accuracy cannot be null');
        }
        $this->container['accuracy'] = $accuracy;

        return $this;
    }

    /**
     * Gets by_label
     *
     * @return array<string,string>|null
     */
    public function getByLabel()
    {
        return $this->container['by_label'];
    }

    /**
     * Sets by_label
     *
     * @param array<string,string>|null $by_label label -> one of {'correct','incorrect','missing','extra'}
     *
     * @return self
     */
    public function setByLabel($by_label)
    {
        if (is_null($by_label)) {
            throw new \InvalidArgumentException('non-nullable by_label cannot be null');
        }
        $this->container['by_label'] = $by_label;

        return $this;
    }

    /**
     * Gets correct_fields
     *
     * @return string[]
     */
    public function getCorrectFields()
    {
        return $this->container['correct_fields'];
    }

    /**
     * Sets correct_fields
     *
     * @param string[] $correct_fields correct_fields
     *
     * @return self
     */
    public function setCorrectFields($correct_fields)
    {
        if (is_null($correct_fields)) {
            throw new \InvalidArgumentException('non-nullable correct_fields cannot be null');
        }
        $this->container['correct_fields'] = $correct_fields;

        return $this;
    }

    /**
     * Gets counts
     *
     * @return \Gemina\Sdk\Model\CountBreakdownModel
     */
    public function getCounts()
    {
        return $this->container['counts'];
    }

    /**
     * Sets counts
     *
     * @param \Gemina\Sdk\Model\CountBreakdownModel $counts counts
     *
     * @return self
     */
    public function setCounts($counts)
    {
        if (is_null($counts)) {
            throw new \InvalidArgumentException('non-nullable counts cannot be null');
        }
        $this->container['counts'] = $counts;

        return $this;
    }

    /**
     * Gets coverage
     *
     * @return float
     */
    public function getCoverage()
    {
        return $this->container['coverage'];
    }

    /**
     * Sets coverage
     *
     * @param float $coverage (tp + fp) / total_expected
     *
     * @return self
     */
    public function setCoverage($coverage)
    {
        if (is_null($coverage)) {
            throw new \InvalidArgumentException('non-nullable coverage cannot be null');
        }
        $this->container['coverage'] = $coverage;

        return $this;
    }

    /**
     * Gets differences
     *
     * @return \Gemina\Sdk\Model\FieldDifferenceModel[]
     */
    public function getDifferences()
    {
        return $this->container['differences'];
    }

    /**
     * Sets differences
     *
     * @param \Gemina\Sdk\Model\FieldDifferenceModel[] $differences differences
     *
     * @return self
     */
    public function setDifferences($differences)
    {
        if (is_null($differences)) {
            throw new \InvalidArgumentException('non-nullable differences cannot be null');
        }
        $this->container['differences'] = $differences;

        return $this;
    }

    /**
     * Gets exact_match
     *
     * @return bool
     */
    public function getExactMatch()
    {
        return $this->container['exact_match'];
    }

    /**
     * Sets exact_match
     *
     * @param bool $exact_match exact_match
     *
     * @return self
     */
    public function setExactMatch($exact_match)
    {
        if (is_null($exact_match)) {
            throw new \InvalidArgumentException('non-nullable exact_match cannot be null');
        }
        $this->container['exact_match'] = $exact_match;

        return $this;
    }

    /**
     * Gets extra_fields
     *
     * @return string[]
     */
    public function getExtraFields()
    {
        return $this->container['extra_fields'];
    }

    /**
     * Sets extra_fields
     *
     * @param string[] $extra_fields extra_fields
     *
     * @return self
     */
    public function setExtraFields($extra_fields)
    {
        if (is_null($extra_fields)) {
            throw new \InvalidArgumentException('non-nullable extra_fields cannot be null');
        }
        $this->container['extra_fields'] = $extra_fields;

        return $this;
    }

    /**
     * Gets f1
     *
     * @return float
     */
    public function getF1()
    {
        return $this->container['f1'];
    }

    /**
     * Sets f1
     *
     * @param float $f1 2 * precision * recall / (precision + recall)
     *
     * @return self
     */
    public function setF1($f1)
    {
        if (is_null($f1)) {
            throw new \InvalidArgumentException('non-nullable f1 cannot be null');
        }
        $this->container['f1'] = $f1;

        return $this;
    }

    /**
     * Gets incorrect_fields
     *
     * @return string[]
     */
    public function getIncorrectFields()
    {
        return $this->container['incorrect_fields'];
    }

    /**
     * Sets incorrect_fields
     *
     * @param string[] $incorrect_fields incorrect_fields
     *
     * @return self
     */
    public function setIncorrectFields($incorrect_fields)
    {
        if (is_null($incorrect_fields)) {
            throw new \InvalidArgumentException('non-nullable incorrect_fields cannot be null');
        }
        $this->container['incorrect_fields'] = $incorrect_fields;

        return $this;
    }

    /**
     * Gets missing_fields
     *
     * @return string[]
     */
    public function getMissingFields()
    {
        return $this->container['missing_fields'];
    }

    /**
     * Sets missing_fields
     *
     * @param string[] $missing_fields missing_fields
     *
     * @return self
     */
    public function setMissingFields($missing_fields)
    {
        if (is_null($missing_fields)) {
            throw new \InvalidArgumentException('non-nullable missing_fields cannot be null');
        }
        $this->container['missing_fields'] = $missing_fields;

        return $this;
    }

    /**
     * Gets precision
     *
     * @return float
     */
    public function getPrecision()
    {
        return $this->container['precision'];
    }

    /**
     * Sets precision
     *
     * @param float $precision tp / (tp + fp)
     *
     * @return self
     */
    public function setPrecision($precision)
    {
        if (is_null($precision)) {
            throw new \InvalidArgumentException('non-nullable precision cannot be null');
        }
        $this->container['precision'] = $precision;

        return $this;
    }

    /**
     * Gets recall
     *
     * @return float
     */
    public function getRecall()
    {
        return $this->container['recall'];
    }

    /**
     * Sets recall
     *
     * @param float $recall tp / (tp + fn)
     *
     * @return self
     */
    public function setRecall($recall)
    {
        if (is_null($recall)) {
            throw new \InvalidArgumentException('non-nullable recall cannot be null');
        }
        $this->container['recall'] = $recall;

        return $this;
    }

    /**
     * Gets strict_f1
     *
     * @return float|null
     */
    public function getStrictF1()
    {
        return $this->container['strict_f1'];
    }

    /**
     * Sets strict_f1
     *
     * @param float|null $strict_f1 2 * strict_precision * recall / (strict_precision + recall)
     *
     * @return self
     */
    public function setStrictF1($strict_f1)
    {
        if (is_null($strict_f1)) {
            array_push($this->openAPINullablesSetToNull, 'strict_f1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('strict_f1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['strict_f1'] = $strict_f1;

        return $this;
    }

    /**
     * Gets strict_precision
     *
     * @return float|null
     */
    public function getStrictPrecision()
    {
        return $this->container['strict_precision'];
    }

    /**
     * Sets strict_precision
     *
     * @param float|null $strict_precision tp / (tp + fp + extra)
     *
     * @return self
     */
    public function setStrictPrecision($strict_precision)
    {
        if (is_null($strict_precision)) {
            array_push($this->openAPINullablesSetToNull, 'strict_precision');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('strict_precision', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['strict_precision'] = $strict_precision;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


