<?php
/**
 * ContractOutDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * ContractOutDTO Class Doc Comment
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ContractOutDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ContractOutDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'billing_cycle_day' => 'int',
        'checkout_url' => 'string',
        'created_at' => '\DateTime',
        'created_at_timestamp' => 'float',
        'id' => 'string',
        'max_monthly_extractions' => 'int',
        'monthly_filetag_credits' => 'int',
        'paddle_subscription_id' => 'string',
        'rate_card_template_id' => 'string',
        'rate_cards' => '\Gemina\Sdk\Model\RateCardOutDTO[]',
        'requires_manual_approval' => 'bool',
        'status' => '\Gemina\Sdk\Model\ContractStatus',
        'user_email' => 'string',
        'user_id' => 'string',
        'volume_discount_tiers' => '\Gemina\Sdk\Model\VolumeDiscountTierOutDTO[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'billing_cycle_day' => null,
        'checkout_url' => null,
        'created_at' => 'date-time',
        'created_at_timestamp' => null,
        'id' => 'uuid',
        'max_monthly_extractions' => null,
        'monthly_filetag_credits' => null,
        'paddle_subscription_id' => null,
        'rate_card_template_id' => 'uuid',
        'rate_cards' => null,
        'requires_manual_approval' => null,
        'status' => null,
        'user_email' => null,
        'user_id' => 'uuid',
        'volume_discount_tiers' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'billing_cycle_day' => false,
        'checkout_url' => true,
        'created_at' => true,
        'created_at_timestamp' => true,
        'id' => false,
        'max_monthly_extractions' => true,
        'monthly_filetag_credits' => false,
        'paddle_subscription_id' => true,
        'rate_card_template_id' => true,
        'rate_cards' => false,
        'requires_manual_approval' => false,
        'status' => false,
        'user_email' => true,
        'user_id' => false,
        'volume_discount_tiers' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'billing_cycle_day' => 'billingCycleDay',
        'checkout_url' => 'checkoutUrl',
        'created_at' => 'createdAt',
        'created_at_timestamp' => 'createdAtTimestamp',
        'id' => 'id',
        'max_monthly_extractions' => 'maxMonthlyExtractions',
        'monthly_filetag_credits' => 'monthlyFiletagCredits',
        'paddle_subscription_id' => 'paddleSubscriptionId',
        'rate_card_template_id' => 'rateCardTemplateId',
        'rate_cards' => 'rateCards',
        'requires_manual_approval' => 'requiresManualApproval',
        'status' => 'status',
        'user_email' => 'userEmail',
        'user_id' => 'userId',
        'volume_discount_tiers' => 'volumeDiscountTiers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'billing_cycle_day' => 'setBillingCycleDay',
        'checkout_url' => 'setCheckoutUrl',
        'created_at' => 'setCreatedAt',
        'created_at_timestamp' => 'setCreatedAtTimestamp',
        'id' => 'setId',
        'max_monthly_extractions' => 'setMaxMonthlyExtractions',
        'monthly_filetag_credits' => 'setMonthlyFiletagCredits',
        'paddle_subscription_id' => 'setPaddleSubscriptionId',
        'rate_card_template_id' => 'setRateCardTemplateId',
        'rate_cards' => 'setRateCards',
        'requires_manual_approval' => 'setRequiresManualApproval',
        'status' => 'setStatus',
        'user_email' => 'setUserEmail',
        'user_id' => 'setUserId',
        'volume_discount_tiers' => 'setVolumeDiscountTiers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'billing_cycle_day' => 'getBillingCycleDay',
        'checkout_url' => 'getCheckoutUrl',
        'created_at' => 'getCreatedAt',
        'created_at_timestamp' => 'getCreatedAtTimestamp',
        'id' => 'getId',
        'max_monthly_extractions' => 'getMaxMonthlyExtractions',
        'monthly_filetag_credits' => 'getMonthlyFiletagCredits',
        'paddle_subscription_id' => 'getPaddleSubscriptionId',
        'rate_card_template_id' => 'getRateCardTemplateId',
        'rate_cards' => 'getRateCards',
        'requires_manual_approval' => 'getRequiresManualApproval',
        'status' => 'getStatus',
        'user_email' => 'getUserEmail',
        'user_id' => 'getUserId',
        'volume_discount_tiers' => 'getVolumeDiscountTiers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('billing_cycle_day', $data ?? [], null);
        $this->setIfExists('checkout_url', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('created_at_timestamp', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('max_monthly_extractions', $data ?? [], null);
        $this->setIfExists('monthly_filetag_credits', $data ?? [], 0);
        $this->setIfExists('paddle_subscription_id', $data ?? [], null);
        $this->setIfExists('rate_card_template_id', $data ?? [], null);
        $this->setIfExists('rate_cards', $data ?? [], null);
        $this->setIfExists('requires_manual_approval', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('user_email', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('volume_discount_tiers', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['billing_cycle_day'] === null) {
            $invalidProperties[] = "'billing_cycle_day' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (!is_null($this->container['monthly_filetag_credits']) && ($this->container['monthly_filetag_credits'] < 0)) {
            $invalidProperties[] = "invalid value for 'monthly_filetag_credits', must be bigger than or equal to 0.";
        }

        if ($this->container['requires_manual_approval'] === null) {
            $invalidProperties[] = "'requires_manual_approval' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['user_id'] === null) {
            $invalidProperties[] = "'user_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets billing_cycle_day
     *
     * @return int
     */
    public function getBillingCycleDay()
    {
        return $this->container['billing_cycle_day'];
    }

    /**
     * Sets billing_cycle_day
     *
     * @param int $billing_cycle_day billing_cycle_day
     *
     * @return self
     */
    public function setBillingCycleDay($billing_cycle_day)
    {
        if (is_null($billing_cycle_day)) {
            throw new \InvalidArgumentException('non-nullable billing_cycle_day cannot be null');
        }
        $this->container['billing_cycle_day'] = $billing_cycle_day;

        return $this;
    }

    /**
     * Gets checkout_url
     *
     * @return string|null
     */
    public function getCheckoutUrl()
    {
        return $this->container['checkout_url'];
    }

    /**
     * Sets checkout_url
     *
     * @param string|null $checkout_url checkout_url
     *
     * @return self
     */
    public function setCheckoutUrl($checkout_url)
    {
        if (is_null($checkout_url)) {
            array_push($this->openAPINullablesSetToNull, 'checkout_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('checkout_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['checkout_url'] = $checkout_url;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            array_push($this->openAPINullablesSetToNull, 'created_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets created_at_timestamp
     *
     * @return float|null
     */
    public function getCreatedAtTimestamp()
    {
        return $this->container['created_at_timestamp'];
    }

    /**
     * Sets created_at_timestamp
     *
     * @param float|null $created_at_timestamp created_at_timestamp
     *
     * @return self
     */
    public function setCreatedAtTimestamp($created_at_timestamp)
    {
        if (is_null($created_at_timestamp)) {
            array_push($this->openAPINullablesSetToNull, 'created_at_timestamp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at_timestamp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at_timestamp'] = $created_at_timestamp;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets max_monthly_extractions
     *
     * @return int|null
     */
    public function getMaxMonthlyExtractions()
    {
        return $this->container['max_monthly_extractions'];
    }

    /**
     * Sets max_monthly_extractions
     *
     * @param int|null $max_monthly_extractions max_monthly_extractions
     *
     * @return self
     */
    public function setMaxMonthlyExtractions($max_monthly_extractions)
    {
        if (is_null($max_monthly_extractions)) {
            array_push($this->openAPINullablesSetToNull, 'max_monthly_extractions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_monthly_extractions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_monthly_extractions'] = $max_monthly_extractions;

        return $this;
    }

    /**
     * Gets monthly_filetag_credits
     *
     * @return int|null
     */
    public function getMonthlyFiletagCredits()
    {
        return $this->container['monthly_filetag_credits'];
    }

    /**
     * Sets monthly_filetag_credits
     *
     * @param int|null $monthly_filetag_credits monthly_filetag_credits
     *
     * @return self
     */
    public function setMonthlyFiletagCredits($monthly_filetag_credits)
    {
        if (is_null($monthly_filetag_credits)) {
            throw new \InvalidArgumentException('non-nullable monthly_filetag_credits cannot be null');
        }

        if (($monthly_filetag_credits < 0)) {
            throw new \InvalidArgumentException('invalid value for $monthly_filetag_credits when calling ContractOutDTO., must be bigger than or equal to 0.');
        }

        $this->container['monthly_filetag_credits'] = $monthly_filetag_credits;

        return $this;
    }

    /**
     * Gets paddle_subscription_id
     *
     * @return string|null
     */
    public function getPaddleSubscriptionId()
    {
        return $this->container['paddle_subscription_id'];
    }

    /**
     * Sets paddle_subscription_id
     *
     * @param string|null $paddle_subscription_id paddle_subscription_id
     *
     * @return self
     */
    public function setPaddleSubscriptionId($paddle_subscription_id)
    {
        if (is_null($paddle_subscription_id)) {
            array_push($this->openAPINullablesSetToNull, 'paddle_subscription_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('paddle_subscription_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['paddle_subscription_id'] = $paddle_subscription_id;

        return $this;
    }

    /**
     * Gets rate_card_template_id
     *
     * @return string|null
     */
    public function getRateCardTemplateId()
    {
        return $this->container['rate_card_template_id'];
    }

    /**
     * Sets rate_card_template_id
     *
     * @param string|null $rate_card_template_id rate_card_template_id
     *
     * @return self
     */
    public function setRateCardTemplateId($rate_card_template_id)
    {
        if (is_null($rate_card_template_id)) {
            array_push($this->openAPINullablesSetToNull, 'rate_card_template_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rate_card_template_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rate_card_template_id'] = $rate_card_template_id;

        return $this;
    }

    /**
     * Gets rate_cards
     *
     * @return \Gemina\Sdk\Model\RateCardOutDTO[]|null
     */
    public function getRateCards()
    {
        return $this->container['rate_cards'];
    }

    /**
     * Sets rate_cards
     *
     * @param \Gemina\Sdk\Model\RateCardOutDTO[]|null $rate_cards rate_cards
     *
     * @return self
     */
    public function setRateCards($rate_cards)
    {
        if (is_null($rate_cards)) {
            throw new \InvalidArgumentException('non-nullable rate_cards cannot be null');
        }
        $this->container['rate_cards'] = $rate_cards;

        return $this;
    }

    /**
     * Gets requires_manual_approval
     *
     * @return bool
     */
    public function getRequiresManualApproval()
    {
        return $this->container['requires_manual_approval'];
    }

    /**
     * Sets requires_manual_approval
     *
     * @param bool $requires_manual_approval requires_manual_approval
     *
     * @return self
     */
    public function setRequiresManualApproval($requires_manual_approval)
    {
        if (is_null($requires_manual_approval)) {
            throw new \InvalidArgumentException('non-nullable requires_manual_approval cannot be null');
        }
        $this->container['requires_manual_approval'] = $requires_manual_approval;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Gemina\Sdk\Model\ContractStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Gemina\Sdk\Model\ContractStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets user_email
     *
     * @return string|null
     */
    public function getUserEmail()
    {
        return $this->container['user_email'];
    }

    /**
     * Sets user_email
     *
     * @param string|null $user_email user_email
     *
     * @return self
     */
    public function setUserEmail($user_email)
    {
        if (is_null($user_email)) {
            array_push($this->openAPINullablesSetToNull, 'user_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_email'] = $user_email;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets volume_discount_tiers
     *
     * @return \Gemina\Sdk\Model\VolumeDiscountTierOutDTO[]|null
     */
    public function getVolumeDiscountTiers()
    {
        return $this->container['volume_discount_tiers'];
    }

    /**
     * Sets volume_discount_tiers
     *
     * @param \Gemina\Sdk\Model\VolumeDiscountTierOutDTO[]|null $volume_discount_tiers volume_discount_tiers
     *
     * @return self
     */
    public function setVolumeDiscountTiers($volume_discount_tiers)
    {
        if (is_null($volume_discount_tiers)) {
            throw new \InvalidArgumentException('non-nullable volume_discount_tiers cannot be null');
        }
        $this->container['volume_discount_tiers'] = $volume_discount_tiers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


