<?php
/**
 * ExtractionValidationMetaOutDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * ExtractionValidationMetaOutDTO Class Doc Comment
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExtractionValidationMetaOutDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ExtractionValidationMetaOutDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'correction' => 'bool',
        'document_id' => 'string',
        'evaluation' => 'bool',
        'extraction_id' => 'string',
        'extraction_type' => '\Gemina\Sdk\Model\ExtractionTypeModel',
        'include_coordinates' => 'bool',
        'model_type' => '\Gemina\Sdk\Model\ModelType',
        'processor_class' => 'string',
        'thinking' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'correction' => null,
        'document_id' => 'uuid',
        'evaluation' => null,
        'extraction_id' => 'uuid',
        'extraction_type' => null,
        'include_coordinates' => null,
        'model_type' => null,
        'processor_class' => null,
        'thinking' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'correction' => false,
        'document_id' => true,
        'evaluation' => false,
        'extraction_id' => true,
        'extraction_type' => false,
        'include_coordinates' => false,
        'model_type' => false,
        'processor_class' => false,
        'thinking' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'correction' => 'correction',
        'document_id' => 'documentId',
        'evaluation' => 'evaluation',
        'extraction_id' => 'extractionId',
        'extraction_type' => 'extractionType',
        'include_coordinates' => 'includeCoordinates',
        'model_type' => 'modelType',
        'processor_class' => 'processorClass',
        'thinking' => 'thinking'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'correction' => 'setCorrection',
        'document_id' => 'setDocumentId',
        'evaluation' => 'setEvaluation',
        'extraction_id' => 'setExtractionId',
        'extraction_type' => 'setExtractionType',
        'include_coordinates' => 'setIncludeCoordinates',
        'model_type' => 'setModelType',
        'processor_class' => 'setProcessorClass',
        'thinking' => 'setThinking'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'correction' => 'getCorrection',
        'document_id' => 'getDocumentId',
        'evaluation' => 'getEvaluation',
        'extraction_id' => 'getExtractionId',
        'extraction_type' => 'getExtractionType',
        'include_coordinates' => 'getIncludeCoordinates',
        'model_type' => 'getModelType',
        'processor_class' => 'getProcessorClass',
        'thinking' => 'getThinking'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('correction', $data ?? [], null);
        $this->setIfExists('document_id', $data ?? [], null);
        $this->setIfExists('evaluation', $data ?? [], null);
        $this->setIfExists('extraction_id', $data ?? [], null);
        $this->setIfExists('extraction_type', $data ?? [], null);
        $this->setIfExists('include_coordinates', $data ?? [], null);
        $this->setIfExists('model_type', $data ?? [], null);
        $this->setIfExists('processor_class', $data ?? [], null);
        $this->setIfExists('thinking', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['correction'] === null) {
            $invalidProperties[] = "'correction' can't be null";
        }
        if ($this->container['evaluation'] === null) {
            $invalidProperties[] = "'evaluation' can't be null";
        }
        if ($this->container['extraction_type'] === null) {
            $invalidProperties[] = "'extraction_type' can't be null";
        }
        if ($this->container['include_coordinates'] === null) {
            $invalidProperties[] = "'include_coordinates' can't be null";
        }
        if ($this->container['model_type'] === null) {
            $invalidProperties[] = "'model_type' can't be null";
        }
        if ($this->container['processor_class'] === null) {
            $invalidProperties[] = "'processor_class' can't be null";
        }
        if ($this->container['thinking'] === null) {
            $invalidProperties[] = "'thinking' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets correction
     *
     * @return bool
     */
    public function getCorrection()
    {
        return $this->container['correction'];
    }

    /**
     * Sets correction
     *
     * @param bool $correction correction
     *
     * @return self
     */
    public function setCorrection($correction)
    {
        if (is_null($correction)) {
            throw new \InvalidArgumentException('non-nullable correction cannot be null');
        }
        $this->container['correction'] = $correction;

        return $this;
    }

    /**
     * Gets document_id
     *
     * @return string|null
     */
    public function getDocumentId()
    {
        return $this->container['document_id'];
    }

    /**
     * Sets document_id
     *
     * @param string|null $document_id document_id
     *
     * @return self
     */
    public function setDocumentId($document_id)
    {
        if (is_null($document_id)) {
            array_push($this->openAPINullablesSetToNull, 'document_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_id'] = $document_id;

        return $this;
    }

    /**
     * Gets evaluation
     *
     * @return bool
     */
    public function getEvaluation()
    {
        return $this->container['evaluation'];
    }

    /**
     * Sets evaluation
     *
     * @param bool $evaluation evaluation
     *
     * @return self
     */
    public function setEvaluation($evaluation)
    {
        if (is_null($evaluation)) {
            throw new \InvalidArgumentException('non-nullable evaluation cannot be null');
        }
        $this->container['evaluation'] = $evaluation;

        return $this;
    }

    /**
     * Gets extraction_id
     *
     * @return string|null
     */
    public function getExtractionId()
    {
        return $this->container['extraction_id'];
    }

    /**
     * Sets extraction_id
     *
     * @param string|null $extraction_id extraction_id
     *
     * @return self
     */
    public function setExtractionId($extraction_id)
    {
        if (is_null($extraction_id)) {
            array_push($this->openAPINullablesSetToNull, 'extraction_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('extraction_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['extraction_id'] = $extraction_id;

        return $this;
    }

    /**
     * Gets extraction_type
     *
     * @return \Gemina\Sdk\Model\ExtractionTypeModel
     */
    public function getExtractionType()
    {
        return $this->container['extraction_type'];
    }

    /**
     * Sets extraction_type
     *
     * @param \Gemina\Sdk\Model\ExtractionTypeModel $extraction_type extraction_type
     *
     * @return self
     */
    public function setExtractionType($extraction_type)
    {
        if (is_null($extraction_type)) {
            throw new \InvalidArgumentException('non-nullable extraction_type cannot be null');
        }
        $this->container['extraction_type'] = $extraction_type;

        return $this;
    }

    /**
     * Gets include_coordinates
     *
     * @return bool
     */
    public function getIncludeCoordinates()
    {
        return $this->container['include_coordinates'];
    }

    /**
     * Sets include_coordinates
     *
     * @param bool $include_coordinates include_coordinates
     *
     * @return self
     */
    public function setIncludeCoordinates($include_coordinates)
    {
        if (is_null($include_coordinates)) {
            throw new \InvalidArgumentException('non-nullable include_coordinates cannot be null');
        }
        $this->container['include_coordinates'] = $include_coordinates;

        return $this;
    }

    /**
     * Gets model_type
     *
     * @return \Gemina\Sdk\Model\ModelType
     */
    public function getModelType()
    {
        return $this->container['model_type'];
    }

    /**
     * Sets model_type
     *
     * @param \Gemina\Sdk\Model\ModelType $model_type model_type
     *
     * @return self
     */
    public function setModelType($model_type)
    {
        if (is_null($model_type)) {
            throw new \InvalidArgumentException('non-nullable model_type cannot be null');
        }
        $this->container['model_type'] = $model_type;

        return $this;
    }

    /**
     * Gets processor_class
     *
     * @return string
     */
    public function getProcessorClass()
    {
        return $this->container['processor_class'];
    }

    /**
     * Sets processor_class
     *
     * @param string $processor_class processor_class
     *
     * @return self
     */
    public function setProcessorClass($processor_class)
    {
        if (is_null($processor_class)) {
            throw new \InvalidArgumentException('non-nullable processor_class cannot be null');
        }
        $this->container['processor_class'] = $processor_class;

        return $this;
    }

    /**
     * Gets thinking
     *
     * @return bool
     */
    public function getThinking()
    {
        return $this->container['thinking'];
    }

    /**
     * Sets thinking
     *
     * @param bool $thinking thinking
     *
     * @return self
     */
    public function setThinking($thinking)
    {
        if (is_null($thinking)) {
            throw new \InvalidArgumentException('non-nullable thinking cannot be null');
        }
        $this->container['thinking'] = $thinking;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


