<?php
/**
 * ExtractionDocumentViewMetaOutDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * ExtractionDocumentViewMetaOutDTO Class Doc Comment
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExtractionDocumentViewMetaOutDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ExtractionDocumentViewMetaOutDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'api_key_id' => 'string',
        'api_key_name' => 'string',
        'content_type' => 'string',
        'document_id' => 'string',
        'end_user_id' => 'string',
        'external_id' => 'string',
        'filename' => 'string',
        'image_url' => 'string',
        'normalized_height' => 'int',
        'normalized_megapixels' => 'float',
        'normalized_width' => 'int',
        'number_of_pages' => 'int',
        'original_document_url' => 'string',
        'storage_location' => '\Gemina\Sdk\Model\DataCenterRegionModel',
        'thumbnail_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'api_key_id' => 'uuid',
        'api_key_name' => null,
        'content_type' => null,
        'document_id' => 'uuid',
        'end_user_id' => null,
        'external_id' => null,
        'filename' => null,
        'image_url' => 'uri',
        'normalized_height' => null,
        'normalized_megapixels' => null,
        'normalized_width' => null,
        'number_of_pages' => null,
        'original_document_url' => 'uri',
        'storage_location' => null,
        'thumbnail_url' => 'uri'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'api_key_id' => true,
        'api_key_name' => true,
        'content_type' => true,
        'document_id' => true,
        'end_user_id' => true,
        'external_id' => true,
        'filename' => true,
        'image_url' => true,
        'normalized_height' => true,
        'normalized_megapixels' => true,
        'normalized_width' => true,
        'number_of_pages' => true,
        'original_document_url' => true,
        'storage_location' => true,
        'thumbnail_url' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'api_key_id' => 'apiKeyId',
        'api_key_name' => 'apiKeyName',
        'content_type' => 'contentType',
        'document_id' => 'documentId',
        'end_user_id' => 'endUserId',
        'external_id' => 'externalId',
        'filename' => 'filename',
        'image_url' => 'imageUrl',
        'normalized_height' => 'normalizedHeight',
        'normalized_megapixels' => 'normalizedMegapixels',
        'normalized_width' => 'normalizedWidth',
        'number_of_pages' => 'numberOfPages',
        'original_document_url' => 'originalDocumentUrl',
        'storage_location' => 'storageLocation',
        'thumbnail_url' => 'thumbnailUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'api_key_id' => 'setApiKeyId',
        'api_key_name' => 'setApiKeyName',
        'content_type' => 'setContentType',
        'document_id' => 'setDocumentId',
        'end_user_id' => 'setEndUserId',
        'external_id' => 'setExternalId',
        'filename' => 'setFilename',
        'image_url' => 'setImageUrl',
        'normalized_height' => 'setNormalizedHeight',
        'normalized_megapixels' => 'setNormalizedMegapixels',
        'normalized_width' => 'setNormalizedWidth',
        'number_of_pages' => 'setNumberOfPages',
        'original_document_url' => 'setOriginalDocumentUrl',
        'storage_location' => 'setStorageLocation',
        'thumbnail_url' => 'setThumbnailUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'api_key_id' => 'getApiKeyId',
        'api_key_name' => 'getApiKeyName',
        'content_type' => 'getContentType',
        'document_id' => 'getDocumentId',
        'end_user_id' => 'getEndUserId',
        'external_id' => 'getExternalId',
        'filename' => 'getFilename',
        'image_url' => 'getImageUrl',
        'normalized_height' => 'getNormalizedHeight',
        'normalized_megapixels' => 'getNormalizedMegapixels',
        'normalized_width' => 'getNormalizedWidth',
        'number_of_pages' => 'getNumberOfPages',
        'original_document_url' => 'getOriginalDocumentUrl',
        'storage_location' => 'getStorageLocation',
        'thumbnail_url' => 'getThumbnailUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('api_key_id', $data ?? [], null);
        $this->setIfExists('api_key_name', $data ?? [], null);
        $this->setIfExists('content_type', $data ?? [], null);
        $this->setIfExists('document_id', $data ?? [], null);
        $this->setIfExists('end_user_id', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('filename', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('normalized_height', $data ?? [], null);
        $this->setIfExists('normalized_megapixels', $data ?? [], null);
        $this->setIfExists('normalized_width', $data ?? [], null);
        $this->setIfExists('number_of_pages', $data ?? [], null);
        $this->setIfExists('original_document_url', $data ?? [], null);
        $this->setIfExists('storage_location', $data ?? [], null);
        $this->setIfExists('thumbnail_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) > 2083)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be smaller than or equal to 2083.";
        }

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) < 1)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['original_document_url']) && (mb_strlen($this->container['original_document_url']) > 2083)) {
            $invalidProperties[] = "invalid value for 'original_document_url', the character length must be smaller than or equal to 2083.";
        }

        if (!is_null($this->container['original_document_url']) && (mb_strlen($this->container['original_document_url']) < 1)) {
            $invalidProperties[] = "invalid value for 'original_document_url', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['thumbnail_url']) && (mb_strlen($this->container['thumbnail_url']) > 2083)) {
            $invalidProperties[] = "invalid value for 'thumbnail_url', the character length must be smaller than or equal to 2083.";
        }

        if (!is_null($this->container['thumbnail_url']) && (mb_strlen($this->container['thumbnail_url']) < 1)) {
            $invalidProperties[] = "invalid value for 'thumbnail_url', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets api_key_id
     *
     * @return string|null
     */
    public function getApiKeyId()
    {
        return $this->container['api_key_id'];
    }

    /**
     * Sets api_key_id
     *
     * @param string|null $api_key_id api_key_id
     *
     * @return self
     */
    public function setApiKeyId($api_key_id)
    {
        if (is_null($api_key_id)) {
            array_push($this->openAPINullablesSetToNull, 'api_key_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_key_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_key_id'] = $api_key_id;

        return $this;
    }

    /**
     * Gets api_key_name
     *
     * @return string|null
     */
    public function getApiKeyName()
    {
        return $this->container['api_key_name'];
    }

    /**
     * Sets api_key_name
     *
     * @param string|null $api_key_name api_key_name
     *
     * @return self
     */
    public function setApiKeyName($api_key_name)
    {
        if (is_null($api_key_name)) {
            array_push($this->openAPINullablesSetToNull, 'api_key_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_key_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_key_name'] = $api_key_name;

        return $this;
    }

    /**
     * Gets content_type
     *
     * @return string|null
     */
    public function getContentType()
    {
        return $this->container['content_type'];
    }

    /**
     * Sets content_type
     *
     * @param string|null $content_type content_type
     *
     * @return self
     */
    public function setContentType($content_type)
    {
        if (is_null($content_type)) {
            array_push($this->openAPINullablesSetToNull, 'content_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('content_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['content_type'] = $content_type;

        return $this;
    }

    /**
     * Gets document_id
     *
     * @return string|null
     */
    public function getDocumentId()
    {
        return $this->container['document_id'];
    }

    /**
     * Sets document_id
     *
     * @param string|null $document_id document_id
     *
     * @return self
     */
    public function setDocumentId($document_id)
    {
        if (is_null($document_id)) {
            array_push($this->openAPINullablesSetToNull, 'document_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_id'] = $document_id;

        return $this;
    }

    /**
     * Gets end_user_id
     *
     * @return string|null
     */
    public function getEndUserId()
    {
        return $this->container['end_user_id'];
    }

    /**
     * Sets end_user_id
     *
     * @param string|null $end_user_id end_user_id
     *
     * @return self
     */
    public function setEndUserId($end_user_id)
    {
        if (is_null($end_user_id)) {
            array_push($this->openAPINullablesSetToNull, 'end_user_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_user_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_user_id'] = $end_user_id;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            array_push($this->openAPINullablesSetToNull, 'external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets filename
     *
     * @return string|null
     */
    public function getFilename()
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string|null $filename filename
     *
     * @return self
     */
    public function setFilename($filename)
    {
        if (is_null($filename)) {
            array_push($this->openAPINullablesSetToNull, 'filename');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filename', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['filename'] = $filename;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($image_url) && (mb_strlen($image_url) > 2083)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling ExtractionDocumentViewMetaOutDTO., must be smaller than or equal to 2083.');
        }
        if (!is_null($image_url) && (mb_strlen($image_url) < 1)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling ExtractionDocumentViewMetaOutDTO., must be bigger than or equal to 1.');
        }

        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets normalized_height
     *
     * @return int|null
     */
    public function getNormalizedHeight()
    {
        return $this->container['normalized_height'];
    }

    /**
     * Sets normalized_height
     *
     * @param int|null $normalized_height normalized_height
     *
     * @return self
     */
    public function setNormalizedHeight($normalized_height)
    {
        if (is_null($normalized_height)) {
            array_push($this->openAPINullablesSetToNull, 'normalized_height');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('normalized_height', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['normalized_height'] = $normalized_height;

        return $this;
    }

    /**
     * Gets normalized_megapixels
     *
     * @return float|null
     */
    public function getNormalizedMegapixels()
    {
        return $this->container['normalized_megapixels'];
    }

    /**
     * Sets normalized_megapixels
     *
     * @param float|null $normalized_megapixels normalized_megapixels
     *
     * @return self
     */
    public function setNormalizedMegapixels($normalized_megapixels)
    {
        if (is_null($normalized_megapixels)) {
            array_push($this->openAPINullablesSetToNull, 'normalized_megapixels');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('normalized_megapixels', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['normalized_megapixels'] = $normalized_megapixels;

        return $this;
    }

    /**
     * Gets normalized_width
     *
     * @return int|null
     */
    public function getNormalizedWidth()
    {
        return $this->container['normalized_width'];
    }

    /**
     * Sets normalized_width
     *
     * @param int|null $normalized_width normalized_width
     *
     * @return self
     */
    public function setNormalizedWidth($normalized_width)
    {
        if (is_null($normalized_width)) {
            array_push($this->openAPINullablesSetToNull, 'normalized_width');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('normalized_width', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['normalized_width'] = $normalized_width;

        return $this;
    }

    /**
     * Gets number_of_pages
     *
     * @return int|null
     */
    public function getNumberOfPages()
    {
        return $this->container['number_of_pages'];
    }

    /**
     * Sets number_of_pages
     *
     * @param int|null $number_of_pages number_of_pages
     *
     * @return self
     */
    public function setNumberOfPages($number_of_pages)
    {
        if (is_null($number_of_pages)) {
            array_push($this->openAPINullablesSetToNull, 'number_of_pages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number_of_pages', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number_of_pages'] = $number_of_pages;

        return $this;
    }

    /**
     * Gets original_document_url
     *
     * @return string|null
     */
    public function getOriginalDocumentUrl()
    {
        return $this->container['original_document_url'];
    }

    /**
     * Sets original_document_url
     *
     * @param string|null $original_document_url original_document_url
     *
     * @return self
     */
    public function setOriginalDocumentUrl($original_document_url)
    {
        if (is_null($original_document_url)) {
            array_push($this->openAPINullablesSetToNull, 'original_document_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('original_document_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($original_document_url) && (mb_strlen($original_document_url) > 2083)) {
            throw new \InvalidArgumentException('invalid length for $original_document_url when calling ExtractionDocumentViewMetaOutDTO., must be smaller than or equal to 2083.');
        }
        if (!is_null($original_document_url) && (mb_strlen($original_document_url) < 1)) {
            throw new \InvalidArgumentException('invalid length for $original_document_url when calling ExtractionDocumentViewMetaOutDTO., must be bigger than or equal to 1.');
        }

        $this->container['original_document_url'] = $original_document_url;

        return $this;
    }

    /**
     * Gets storage_location
     *
     * @return \Gemina\Sdk\Model\DataCenterRegionModel|null
     */
    public function getStorageLocation()
    {
        return $this->container['storage_location'];
    }

    /**
     * Sets storage_location
     *
     * @param \Gemina\Sdk\Model\DataCenterRegionModel|null $storage_location storage_location
     *
     * @return self
     */
    public function setStorageLocation($storage_location)
    {
        if (is_null($storage_location)) {
            array_push($this->openAPINullablesSetToNull, 'storage_location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('storage_location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['storage_location'] = $storage_location;

        return $this;
    }

    /**
     * Gets thumbnail_url
     *
     * @return string|null
     */
    public function getThumbnailUrl()
    {
        return $this->container['thumbnail_url'];
    }

    /**
     * Sets thumbnail_url
     *
     * @param string|null $thumbnail_url thumbnail_url
     *
     * @return self
     */
    public function setThumbnailUrl($thumbnail_url)
    {
        if (is_null($thumbnail_url)) {
            array_push($this->openAPINullablesSetToNull, 'thumbnail_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('thumbnail_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($thumbnail_url) && (mb_strlen($thumbnail_url) > 2083)) {
            throw new \InvalidArgumentException('invalid length for $thumbnail_url when calling ExtractionDocumentViewMetaOutDTO., must be smaller than or equal to 2083.');
        }
        if (!is_null($thumbnail_url) && (mb_strlen($thumbnail_url) < 1)) {
            throw new \InvalidArgumentException('invalid length for $thumbnail_url when calling ExtractionDocumentViewMetaOutDTO., must be bigger than or equal to 1.');
        }

        $this->container['thumbnail_url'] = $thumbnail_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


