<?php
/**
 * FileTagFilenamePatternsOutDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * FileTagFilenamePatternsOutDTO Class Doc Comment
 *
 * @category Class
 * @description Suggested filename patterns produced by &#x60;&#x60;generate_filename_patterns&#x60;&#x60;.  Six variants are surfaced so the caller can pick the layout that best matches their downstream filing system. Long forms (&#x60;&#x60;*_full&#x60;&#x60;) preserve the full extracted metadata; short forms truncate to a sensible length.
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FileTagFilenamePatternsOutDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'FileTagFilenamePatternsOutDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'date_first' => 'string',
        'date_first_full' => 'string',
        'type_first' => 'string',
        'type_first_full' => 'string',
        'vendor_first' => 'string',
        'vendor_first_full' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'date_first' => null,
        'date_first_full' => null,
        'type_first' => null,
        'type_first_full' => null,
        'vendor_first' => null,
        'vendor_first_full' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'date_first' => false,
        'date_first_full' => false,
        'type_first' => false,
        'type_first_full' => false,
        'vendor_first' => false,
        'vendor_first_full' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date_first' => 'date_first',
        'date_first_full' => 'date_first_full',
        'type_first' => 'type_first',
        'type_first_full' => 'type_first_full',
        'vendor_first' => 'vendor_first',
        'vendor_first_full' => 'vendor_first_full'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date_first' => 'setDateFirst',
        'date_first_full' => 'setDateFirstFull',
        'type_first' => 'setTypeFirst',
        'type_first_full' => 'setTypeFirstFull',
        'vendor_first' => 'setVendorFirst',
        'vendor_first_full' => 'setVendorFirstFull'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date_first' => 'getDateFirst',
        'date_first_full' => 'getDateFirstFull',
        'type_first' => 'getTypeFirst',
        'type_first_full' => 'getTypeFirstFull',
        'vendor_first' => 'getVendorFirst',
        'vendor_first_full' => 'getVendorFirstFull'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date_first', $data ?? [], null);
        $this->setIfExists('date_first_full', $data ?? [], null);
        $this->setIfExists('type_first', $data ?? [], null);
        $this->setIfExists('type_first_full', $data ?? [], null);
        $this->setIfExists('vendor_first', $data ?? [], null);
        $this->setIfExists('vendor_first_full', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['date_first'] === null) {
            $invalidProperties[] = "'date_first' can't be null";
        }
        if ($this->container['date_first_full'] === null) {
            $invalidProperties[] = "'date_first_full' can't be null";
        }
        if ($this->container['type_first'] === null) {
            $invalidProperties[] = "'type_first' can't be null";
        }
        if ($this->container['type_first_full'] === null) {
            $invalidProperties[] = "'type_first_full' can't be null";
        }
        if ($this->container['vendor_first'] === null) {
            $invalidProperties[] = "'vendor_first' can't be null";
        }
        if ($this->container['vendor_first_full'] === null) {
            $invalidProperties[] = "'vendor_first_full' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date_first
     *
     * @return string
     */
    public function getDateFirst()
    {
        return $this->container['date_first'];
    }

    /**
     * Sets date_first
     *
     * @param string $date_first date_first
     *
     * @return self
     */
    public function setDateFirst($date_first)
    {
        if (is_null($date_first)) {
            throw new \InvalidArgumentException('non-nullable date_first cannot be null');
        }
        $this->container['date_first'] = $date_first;

        return $this;
    }

    /**
     * Gets date_first_full
     *
     * @return string
     */
    public function getDateFirstFull()
    {
        return $this->container['date_first_full'];
    }

    /**
     * Sets date_first_full
     *
     * @param string $date_first_full date_first_full
     *
     * @return self
     */
    public function setDateFirstFull($date_first_full)
    {
        if (is_null($date_first_full)) {
            throw new \InvalidArgumentException('non-nullable date_first_full cannot be null');
        }
        $this->container['date_first_full'] = $date_first_full;

        return $this;
    }

    /**
     * Gets type_first
     *
     * @return string
     */
    public function getTypeFirst()
    {
        return $this->container['type_first'];
    }

    /**
     * Sets type_first
     *
     * @param string $type_first type_first
     *
     * @return self
     */
    public function setTypeFirst($type_first)
    {
        if (is_null($type_first)) {
            throw new \InvalidArgumentException('non-nullable type_first cannot be null');
        }
        $this->container['type_first'] = $type_first;

        return $this;
    }

    /**
     * Gets type_first_full
     *
     * @return string
     */
    public function getTypeFirstFull()
    {
        return $this->container['type_first_full'];
    }

    /**
     * Sets type_first_full
     *
     * @param string $type_first_full type_first_full
     *
     * @return self
     */
    public function setTypeFirstFull($type_first_full)
    {
        if (is_null($type_first_full)) {
            throw new \InvalidArgumentException('non-nullable type_first_full cannot be null');
        }
        $this->container['type_first_full'] = $type_first_full;

        return $this;
    }

    /**
     * Gets vendor_first
     *
     * @return string
     */
    public function getVendorFirst()
    {
        return $this->container['vendor_first'];
    }

    /**
     * Sets vendor_first
     *
     * @param string $vendor_first vendor_first
     *
     * @return self
     */
    public function setVendorFirst($vendor_first)
    {
        if (is_null($vendor_first)) {
            throw new \InvalidArgumentException('non-nullable vendor_first cannot be null');
        }
        $this->container['vendor_first'] = $vendor_first;

        return $this;
    }

    /**
     * Gets vendor_first_full
     *
     * @return string
     */
    public function getVendorFirstFull()
    {
        return $this->container['vendor_first_full'];
    }

    /**
     * Sets vendor_first_full
     *
     * @param string $vendor_first_full vendor_first_full
     *
     * @return self
     */
    public function setVendorFirstFull($vendor_first_full)
    {
        if (is_null($vendor_first_full)) {
            throw new \InvalidArgumentException('non-nullable vendor_first_full cannot be null');
        }
        $this->container['vendor_first_full'] = $vendor_first_full;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


