<?php
/**
 * FileTagBalanceOutDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * FileTagBalanceOutDTO Class Doc Comment
 *
 * @category Class
 * @description Current user&#39;s FileTag balance + allowance for the dashboard surface.
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FileTagBalanceOutDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'FileTagBalanceOutDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'anniversary_day' => 'int',
        'credits_granted_at' => '\DateTime',
        'credits_remaining' => 'string',
        'monthly_allowance' => 'string',
        'resets_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'anniversary_day' => null,
        'credits_granted_at' => 'date-time',
        'credits_remaining' => null,
        'monthly_allowance' => null,
        'resets_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'anniversary_day' => false,
        'credits_granted_at' => false,
        'credits_remaining' => false,
        'monthly_allowance' => false,
        'resets_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'anniversary_day' => 'anniversaryDay',
        'credits_granted_at' => 'creditsGrantedAt',
        'credits_remaining' => 'creditsRemaining',
        'monthly_allowance' => 'monthlyAllowance',
        'resets_at' => 'resetsAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'anniversary_day' => 'setAnniversaryDay',
        'credits_granted_at' => 'setCreditsGrantedAt',
        'credits_remaining' => 'setCreditsRemaining',
        'monthly_allowance' => 'setMonthlyAllowance',
        'resets_at' => 'setResetsAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'anniversary_day' => 'getAnniversaryDay',
        'credits_granted_at' => 'getCreditsGrantedAt',
        'credits_remaining' => 'getCreditsRemaining',
        'monthly_allowance' => 'getMonthlyAllowance',
        'resets_at' => 'getResetsAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('anniversary_day', $data ?? [], null);
        $this->setIfExists('credits_granted_at', $data ?? [], null);
        $this->setIfExists('credits_remaining', $data ?? [], null);
        $this->setIfExists('monthly_allowance', $data ?? [], null);
        $this->setIfExists('resets_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['anniversary_day'] === null) {
            $invalidProperties[] = "'anniversary_day' can't be null";
        }
        if ($this->container['credits_granted_at'] === null) {
            $invalidProperties[] = "'credits_granted_at' can't be null";
        }
        if ($this->container['credits_remaining'] === null) {
            $invalidProperties[] = "'credits_remaining' can't be null";
        }
        if ($this->container['monthly_allowance'] === null) {
            $invalidProperties[] = "'monthly_allowance' can't be null";
        }
        if ($this->container['resets_at'] === null) {
            $invalidProperties[] = "'resets_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets anniversary_day
     *
     * @return int
     */
    public function getAnniversaryDay()
    {
        return $this->container['anniversary_day'];
    }

    /**
     * Sets anniversary_day
     *
     * @param int $anniversary_day anniversary_day
     *
     * @return self
     */
    public function setAnniversaryDay($anniversary_day)
    {
        if (is_null($anniversary_day)) {
            throw new \InvalidArgumentException('non-nullable anniversary_day cannot be null');
        }
        $this->container['anniversary_day'] = $anniversary_day;

        return $this;
    }

    /**
     * Gets credits_granted_at
     *
     * @return \DateTime
     */
    public function getCreditsGrantedAt()
    {
        return $this->container['credits_granted_at'];
    }

    /**
     * Sets credits_granted_at
     *
     * @param \DateTime $credits_granted_at credits_granted_at
     *
     * @return self
     */
    public function setCreditsGrantedAt($credits_granted_at)
    {
        if (is_null($credits_granted_at)) {
            throw new \InvalidArgumentException('non-nullable credits_granted_at cannot be null');
        }
        $this->container['credits_granted_at'] = $credits_granted_at;

        return $this;
    }

    /**
     * Gets credits_remaining
     *
     * @return string
     */
    public function getCreditsRemaining()
    {
        return $this->container['credits_remaining'];
    }

    /**
     * Sets credits_remaining
     *
     * @param string $credits_remaining credits_remaining
     *
     * @return self
     */
    public function setCreditsRemaining($credits_remaining)
    {
        if (is_null($credits_remaining)) {
            throw new \InvalidArgumentException('non-nullable credits_remaining cannot be null');
        }
        $this->container['credits_remaining'] = $credits_remaining;

        return $this;
    }

    /**
     * Gets monthly_allowance
     *
     * @return string
     */
    public function getMonthlyAllowance()
    {
        return $this->container['monthly_allowance'];
    }

    /**
     * Sets monthly_allowance
     *
     * @param string $monthly_allowance monthly_allowance
     *
     * @return self
     */
    public function setMonthlyAllowance($monthly_allowance)
    {
        if (is_null($monthly_allowance)) {
            throw new \InvalidArgumentException('non-nullable monthly_allowance cannot be null');
        }
        $this->container['monthly_allowance'] = $monthly_allowance;

        return $this;
    }

    /**
     * Gets resets_at
     *
     * @return \DateTime
     */
    public function getResetsAt()
    {
        return $this->container['resets_at'];
    }

    /**
     * Sets resets_at
     *
     * @param \DateTime $resets_at resets_at
     *
     * @return self
     */
    public function setResetsAt($resets_at)
    {
        if (is_null($resets_at)) {
            throw new \InvalidArgumentException('non-nullable resets_at cannot be null');
        }
        $this->container['resets_at'] = $resets_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


