<?php
/**
 * ResponseChangePlan
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * ResponseChangePlan Class Doc Comment
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResponseChangePlan implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Response_Change_Plan';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'checkout_url' => 'string',
        'created_at' => '\DateTime',
        'created_at_timestamp' => 'float',
        'paddle_transaction_id' => 'string',
        'subscription_id' => 'string',
        'cancel_scheduled_at' => '\DateTime',
        'credits_remaining' => 'string',
        'credits_snapshot' => 'int',
        'current_period_end' => '\DateTime',
        'current_period_start' => '\DateTime',
        'data_residency_enabled' => 'bool',
        'enhanced_privacy_enabled' => 'bool',
        'id' => 'string',
        'ip_allowlist_enabled' => 'bool',
        'max_data_retention_period' => '\Gemina\Sdk\Model\DataRetentionPeriodModel',
        'max_templates' => 'int',
        'monthly_filetag_credits' => 'int',
        'paddle_subscription_id' => 'string',
        'plan_id' => 'string',
        'plan_name' => 'string',
        'price_snapshot_cents' => 'int',
        'status' => '\Gemina\Sdk\Model\SubscriptionStatus',
        'support_level' => '\Gemina\Sdk\Model\SupportLevel',
        'user_email' => 'string',
        'user_id' => 'string',
        'webhooks_enabled' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'checkout_url' => null,
        'created_at' => 'date-time',
        'created_at_timestamp' => null,
        'paddle_transaction_id' => null,
        'subscription_id' => 'uuid',
        'cancel_scheduled_at' => 'date-time',
        'credits_remaining' => null,
        'credits_snapshot' => null,
        'current_period_end' => 'date-time',
        'current_period_start' => 'date-time',
        'data_residency_enabled' => null,
        'enhanced_privacy_enabled' => null,
        'id' => 'uuid',
        'ip_allowlist_enabled' => null,
        'max_data_retention_period' => null,
        'max_templates' => null,
        'monthly_filetag_credits' => null,
        'paddle_subscription_id' => null,
        'plan_id' => 'uuid',
        'plan_name' => null,
        'price_snapshot_cents' => null,
        'status' => null,
        'support_level' => null,
        'user_email' => null,
        'user_id' => 'uuid',
        'webhooks_enabled' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'checkout_url' => false,
        'created_at' => false,
        'created_at_timestamp' => false,
        'paddle_transaction_id' => false,
        'subscription_id' => false,
        'cancel_scheduled_at' => false,
        'credits_remaining' => false,
        'credits_snapshot' => false,
        'current_period_end' => false,
        'current_period_start' => false,
        'data_residency_enabled' => false,
        'enhanced_privacy_enabled' => false,
        'id' => false,
        'ip_allowlist_enabled' => false,
        'max_data_retention_period' => false,
        'max_templates' => false,
        'monthly_filetag_credits' => false,
        'paddle_subscription_id' => false,
        'plan_id' => false,
        'plan_name' => false,
        'price_snapshot_cents' => false,
        'status' => false,
        'support_level' => false,
        'user_email' => false,
        'user_id' => false,
        'webhooks_enabled' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'checkout_url' => 'checkoutUrl',
        'created_at' => 'createdAt',
        'created_at_timestamp' => 'createdAtTimestamp',
        'paddle_transaction_id' => 'paddleTransactionId',
        'subscription_id' => 'subscriptionId',
        'cancel_scheduled_at' => 'cancelScheduledAt',
        'credits_remaining' => 'creditsRemaining',
        'credits_snapshot' => 'creditsSnapshot',
        'current_period_end' => 'currentPeriodEnd',
        'current_period_start' => 'currentPeriodStart',
        'data_residency_enabled' => 'dataResidencyEnabled',
        'enhanced_privacy_enabled' => 'enhancedPrivacyEnabled',
        'id' => 'id',
        'ip_allowlist_enabled' => 'ipAllowlistEnabled',
        'max_data_retention_period' => 'maxDataRetentionPeriod',
        'max_templates' => 'maxTemplates',
        'monthly_filetag_credits' => 'monthlyFiletagCredits',
        'paddle_subscription_id' => 'paddleSubscriptionId',
        'plan_id' => 'planId',
        'plan_name' => 'planName',
        'price_snapshot_cents' => 'priceSnapshotCents',
        'status' => 'status',
        'support_level' => 'supportLevel',
        'user_email' => 'userEmail',
        'user_id' => 'userId',
        'webhooks_enabled' => 'webhooksEnabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'checkout_url' => 'setCheckoutUrl',
        'created_at' => 'setCreatedAt',
        'created_at_timestamp' => 'setCreatedAtTimestamp',
        'paddle_transaction_id' => 'setPaddleTransactionId',
        'subscription_id' => 'setSubscriptionId',
        'cancel_scheduled_at' => 'setCancelScheduledAt',
        'credits_remaining' => 'setCreditsRemaining',
        'credits_snapshot' => 'setCreditsSnapshot',
        'current_period_end' => 'setCurrentPeriodEnd',
        'current_period_start' => 'setCurrentPeriodStart',
        'data_residency_enabled' => 'setDataResidencyEnabled',
        'enhanced_privacy_enabled' => 'setEnhancedPrivacyEnabled',
        'id' => 'setId',
        'ip_allowlist_enabled' => 'setIpAllowlistEnabled',
        'max_data_retention_period' => 'setMaxDataRetentionPeriod',
        'max_templates' => 'setMaxTemplates',
        'monthly_filetag_credits' => 'setMonthlyFiletagCredits',
        'paddle_subscription_id' => 'setPaddleSubscriptionId',
        'plan_id' => 'setPlanId',
        'plan_name' => 'setPlanName',
        'price_snapshot_cents' => 'setPriceSnapshotCents',
        'status' => 'setStatus',
        'support_level' => 'setSupportLevel',
        'user_email' => 'setUserEmail',
        'user_id' => 'setUserId',
        'webhooks_enabled' => 'setWebhooksEnabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'checkout_url' => 'getCheckoutUrl',
        'created_at' => 'getCreatedAt',
        'created_at_timestamp' => 'getCreatedAtTimestamp',
        'paddle_transaction_id' => 'getPaddleTransactionId',
        'subscription_id' => 'getSubscriptionId',
        'cancel_scheduled_at' => 'getCancelScheduledAt',
        'credits_remaining' => 'getCreditsRemaining',
        'credits_snapshot' => 'getCreditsSnapshot',
        'current_period_end' => 'getCurrentPeriodEnd',
        'current_period_start' => 'getCurrentPeriodStart',
        'data_residency_enabled' => 'getDataResidencyEnabled',
        'enhanced_privacy_enabled' => 'getEnhancedPrivacyEnabled',
        'id' => 'getId',
        'ip_allowlist_enabled' => 'getIpAllowlistEnabled',
        'max_data_retention_period' => 'getMaxDataRetentionPeriod',
        'max_templates' => 'getMaxTemplates',
        'monthly_filetag_credits' => 'getMonthlyFiletagCredits',
        'paddle_subscription_id' => 'getPaddleSubscriptionId',
        'plan_id' => 'getPlanId',
        'plan_name' => 'getPlanName',
        'price_snapshot_cents' => 'getPriceSnapshotCents',
        'status' => 'getStatus',
        'support_level' => 'getSupportLevel',
        'user_email' => 'getUserEmail',
        'user_id' => 'getUserId',
        'webhooks_enabled' => 'getWebhooksEnabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('checkout_url', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('created_at_timestamp', $data ?? [], null);
        $this->setIfExists('paddle_transaction_id', $data ?? [], null);
        $this->setIfExists('subscription_id', $data ?? [], null);
        $this->setIfExists('cancel_scheduled_at', $data ?? [], null);
        $this->setIfExists('credits_remaining', $data ?? [], null);
        $this->setIfExists('credits_snapshot', $data ?? [], null);
        $this->setIfExists('current_period_end', $data ?? [], null);
        $this->setIfExists('current_period_start', $data ?? [], null);
        $this->setIfExists('data_residency_enabled', $data ?? [], null);
        $this->setIfExists('enhanced_privacy_enabled', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('ip_allowlist_enabled', $data ?? [], null);
        $this->setIfExists('max_data_retention_period', $data ?? [], null);
        $this->setIfExists('max_templates', $data ?? [], null);
        $this->setIfExists('monthly_filetag_credits', $data ?? [], null);
        $this->setIfExists('paddle_subscription_id', $data ?? [], null);
        $this->setIfExists('plan_id', $data ?? [], null);
        $this->setIfExists('plan_name', $data ?? [], null);
        $this->setIfExists('price_snapshot_cents', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('support_level', $data ?? [], null);
        $this->setIfExists('user_email', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('webhooks_enabled', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['subscription_id'] === null) {
            $invalidProperties[] = "'subscription_id' can't be null";
        }
        if ($this->container['credits_remaining'] === null) {
            $invalidProperties[] = "'credits_remaining' can't be null";
        }
        if ($this->container['credits_snapshot'] === null) {
            $invalidProperties[] = "'credits_snapshot' can't be null";
        }
        if ($this->container['data_residency_enabled'] === null) {
            $invalidProperties[] = "'data_residency_enabled' can't be null";
        }
        if ($this->container['enhanced_privacy_enabled'] === null) {
            $invalidProperties[] = "'enhanced_privacy_enabled' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['ip_allowlist_enabled'] === null) {
            $invalidProperties[] = "'ip_allowlist_enabled' can't be null";
        }
        if ($this->container['max_data_retention_period'] === null) {
            $invalidProperties[] = "'max_data_retention_period' can't be null";
        }
        if ($this->container['max_templates'] === null) {
            $invalidProperties[] = "'max_templates' can't be null";
        }
        if ($this->container['monthly_filetag_credits'] === null) {
            $invalidProperties[] = "'monthly_filetag_credits' can't be null";
        }
        if ($this->container['plan_id'] === null) {
            $invalidProperties[] = "'plan_id' can't be null";
        }
        if ($this->container['price_snapshot_cents'] === null) {
            $invalidProperties[] = "'price_snapshot_cents' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['support_level'] === null) {
            $invalidProperties[] = "'support_level' can't be null";
        }
        if ($this->container['user_id'] === null) {
            $invalidProperties[] = "'user_id' can't be null";
        }
        if ($this->container['webhooks_enabled'] === null) {
            $invalidProperties[] = "'webhooks_enabled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets checkout_url
     *
     * @return string|null
     */
    public function getCheckoutUrl()
    {
        return $this->container['checkout_url'];
    }

    /**
     * Sets checkout_url
     *
     * @param string|null $checkout_url checkout_url
     *
     * @return self
     */
    public function setCheckoutUrl($checkout_url)
    {
        if (is_null($checkout_url)) {
            throw new \InvalidArgumentException('non-nullable checkout_url cannot be null');
        }
        $this->container['checkout_url'] = $checkout_url;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets created_at_timestamp
     *
     * @return float|null
     */
    public function getCreatedAtTimestamp()
    {
        return $this->container['created_at_timestamp'];
    }

    /**
     * Sets created_at_timestamp
     *
     * @param float|null $created_at_timestamp created_at_timestamp
     *
     * @return self
     */
    public function setCreatedAtTimestamp($created_at_timestamp)
    {
        if (is_null($created_at_timestamp)) {
            throw new \InvalidArgumentException('non-nullable created_at_timestamp cannot be null');
        }
        $this->container['created_at_timestamp'] = $created_at_timestamp;

        return $this;
    }

    /**
     * Gets paddle_transaction_id
     *
     * @return string|null
     */
    public function getPaddleTransactionId()
    {
        return $this->container['paddle_transaction_id'];
    }

    /**
     * Sets paddle_transaction_id
     *
     * @param string|null $paddle_transaction_id paddle_transaction_id
     *
     * @return self
     */
    public function setPaddleTransactionId($paddle_transaction_id)
    {
        if (is_null($paddle_transaction_id)) {
            throw new \InvalidArgumentException('non-nullable paddle_transaction_id cannot be null');
        }
        $this->container['paddle_transaction_id'] = $paddle_transaction_id;

        return $this;
    }

    /**
     * Gets subscription_id
     *
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->container['subscription_id'];
    }

    /**
     * Sets subscription_id
     *
     * @param string $subscription_id subscription_id
     *
     * @return self
     */
    public function setSubscriptionId($subscription_id)
    {
        if (is_null($subscription_id)) {
            throw new \InvalidArgumentException('non-nullable subscription_id cannot be null');
        }
        $this->container['subscription_id'] = $subscription_id;

        return $this;
    }

    /**
     * Gets cancel_scheduled_at
     *
     * @return \DateTime|null
     */
    public function getCancelScheduledAt()
    {
        return $this->container['cancel_scheduled_at'];
    }

    /**
     * Sets cancel_scheduled_at
     *
     * @param \DateTime|null $cancel_scheduled_at cancel_scheduled_at
     *
     * @return self
     */
    public function setCancelScheduledAt($cancel_scheduled_at)
    {
        if (is_null($cancel_scheduled_at)) {
            throw new \InvalidArgumentException('non-nullable cancel_scheduled_at cannot be null');
        }
        $this->container['cancel_scheduled_at'] = $cancel_scheduled_at;

        return $this;
    }

    /**
     * Gets credits_remaining
     *
     * @return string
     */
    public function getCreditsRemaining()
    {
        return $this->container['credits_remaining'];
    }

    /**
     * Sets credits_remaining
     *
     * @param string $credits_remaining credits_remaining
     *
     * @return self
     */
    public function setCreditsRemaining($credits_remaining)
    {
        if (is_null($credits_remaining)) {
            throw new \InvalidArgumentException('non-nullable credits_remaining cannot be null');
        }
        $this->container['credits_remaining'] = $credits_remaining;

        return $this;
    }

    /**
     * Gets credits_snapshot
     *
     * @return int
     */
    public function getCreditsSnapshot()
    {
        return $this->container['credits_snapshot'];
    }

    /**
     * Sets credits_snapshot
     *
     * @param int $credits_snapshot credits_snapshot
     *
     * @return self
     */
    public function setCreditsSnapshot($credits_snapshot)
    {
        if (is_null($credits_snapshot)) {
            throw new \InvalidArgumentException('non-nullable credits_snapshot cannot be null');
        }
        $this->container['credits_snapshot'] = $credits_snapshot;

        return $this;
    }

    /**
     * Gets current_period_end
     *
     * @return \DateTime|null
     */
    public function getCurrentPeriodEnd()
    {
        return $this->container['current_period_end'];
    }

    /**
     * Sets current_period_end
     *
     * @param \DateTime|null $current_period_end current_period_end
     *
     * @return self
     */
    public function setCurrentPeriodEnd($current_period_end)
    {
        if (is_null($current_period_end)) {
            throw new \InvalidArgumentException('non-nullable current_period_end cannot be null');
        }
        $this->container['current_period_end'] = $current_period_end;

        return $this;
    }

    /**
     * Gets current_period_start
     *
     * @return \DateTime|null
     */
    public function getCurrentPeriodStart()
    {
        return $this->container['current_period_start'];
    }

    /**
     * Sets current_period_start
     *
     * @param \DateTime|null $current_period_start current_period_start
     *
     * @return self
     */
    public function setCurrentPeriodStart($current_period_start)
    {
        if (is_null($current_period_start)) {
            throw new \InvalidArgumentException('non-nullable current_period_start cannot be null');
        }
        $this->container['current_period_start'] = $current_period_start;

        return $this;
    }

    /**
     * Gets data_residency_enabled
     *
     * @return bool
     */
    public function getDataResidencyEnabled()
    {
        return $this->container['data_residency_enabled'];
    }

    /**
     * Sets data_residency_enabled
     *
     * @param bool $data_residency_enabled data_residency_enabled
     *
     * @return self
     */
    public function setDataResidencyEnabled($data_residency_enabled)
    {
        if (is_null($data_residency_enabled)) {
            throw new \InvalidArgumentException('non-nullable data_residency_enabled cannot be null');
        }
        $this->container['data_residency_enabled'] = $data_residency_enabled;

        return $this;
    }

    /**
     * Gets enhanced_privacy_enabled
     *
     * @return bool
     */
    public function getEnhancedPrivacyEnabled()
    {
        return $this->container['enhanced_privacy_enabled'];
    }

    /**
     * Sets enhanced_privacy_enabled
     *
     * @param bool $enhanced_privacy_enabled enhanced_privacy_enabled
     *
     * @return self
     */
    public function setEnhancedPrivacyEnabled($enhanced_privacy_enabled)
    {
        if (is_null($enhanced_privacy_enabled)) {
            throw new \InvalidArgumentException('non-nullable enhanced_privacy_enabled cannot be null');
        }
        $this->container['enhanced_privacy_enabled'] = $enhanced_privacy_enabled;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets ip_allowlist_enabled
     *
     * @return bool
     */
    public function getIpAllowlistEnabled()
    {
        return $this->container['ip_allowlist_enabled'];
    }

    /**
     * Sets ip_allowlist_enabled
     *
     * @param bool $ip_allowlist_enabled ip_allowlist_enabled
     *
     * @return self
     */
    public function setIpAllowlistEnabled($ip_allowlist_enabled)
    {
        if (is_null($ip_allowlist_enabled)) {
            throw new \InvalidArgumentException('non-nullable ip_allowlist_enabled cannot be null');
        }
        $this->container['ip_allowlist_enabled'] = $ip_allowlist_enabled;

        return $this;
    }

    /**
     * Gets max_data_retention_period
     *
     * @return \Gemina\Sdk\Model\DataRetentionPeriodModel
     */
    public function getMaxDataRetentionPeriod()
    {
        return $this->container['max_data_retention_period'];
    }

    /**
     * Sets max_data_retention_period
     *
     * @param \Gemina\Sdk\Model\DataRetentionPeriodModel $max_data_retention_period max_data_retention_period
     *
     * @return self
     */
    public function setMaxDataRetentionPeriod($max_data_retention_period)
    {
        if (is_null($max_data_retention_period)) {
            throw new \InvalidArgumentException('non-nullable max_data_retention_period cannot be null');
        }
        $this->container['max_data_retention_period'] = $max_data_retention_period;

        return $this;
    }

    /**
     * Gets max_templates
     *
     * @return int
     */
    public function getMaxTemplates()
    {
        return $this->container['max_templates'];
    }

    /**
     * Sets max_templates
     *
     * @param int $max_templates max_templates
     *
     * @return self
     */
    public function setMaxTemplates($max_templates)
    {
        if (is_null($max_templates)) {
            throw new \InvalidArgumentException('non-nullable max_templates cannot be null');
        }
        $this->container['max_templates'] = $max_templates;

        return $this;
    }

    /**
     * Gets monthly_filetag_credits
     *
     * @return int
     */
    public function getMonthlyFiletagCredits()
    {
        return $this->container['monthly_filetag_credits'];
    }

    /**
     * Sets monthly_filetag_credits
     *
     * @param int $monthly_filetag_credits monthly_filetag_credits
     *
     * @return self
     */
    public function setMonthlyFiletagCredits($monthly_filetag_credits)
    {
        if (is_null($monthly_filetag_credits)) {
            throw new \InvalidArgumentException('non-nullable monthly_filetag_credits cannot be null');
        }
        $this->container['monthly_filetag_credits'] = $monthly_filetag_credits;

        return $this;
    }

    /**
     * Gets paddle_subscription_id
     *
     * @return string|null
     */
    public function getPaddleSubscriptionId()
    {
        return $this->container['paddle_subscription_id'];
    }

    /**
     * Sets paddle_subscription_id
     *
     * @param string|null $paddle_subscription_id paddle_subscription_id
     *
     * @return self
     */
    public function setPaddleSubscriptionId($paddle_subscription_id)
    {
        if (is_null($paddle_subscription_id)) {
            throw new \InvalidArgumentException('non-nullable paddle_subscription_id cannot be null');
        }
        $this->container['paddle_subscription_id'] = $paddle_subscription_id;

        return $this;
    }

    /**
     * Gets plan_id
     *
     * @return string
     */
    public function getPlanId()
    {
        return $this->container['plan_id'];
    }

    /**
     * Sets plan_id
     *
     * @param string $plan_id plan_id
     *
     * @return self
     */
    public function setPlanId($plan_id)
    {
        if (is_null($plan_id)) {
            throw new \InvalidArgumentException('non-nullable plan_id cannot be null');
        }
        $this->container['plan_id'] = $plan_id;

        return $this;
    }

    /**
     * Gets plan_name
     *
     * @return string|null
     */
    public function getPlanName()
    {
        return $this->container['plan_name'];
    }

    /**
     * Sets plan_name
     *
     * @param string|null $plan_name plan_name
     *
     * @return self
     */
    public function setPlanName($plan_name)
    {
        if (is_null($plan_name)) {
            throw new \InvalidArgumentException('non-nullable plan_name cannot be null');
        }
        $this->container['plan_name'] = $plan_name;

        return $this;
    }

    /**
     * Gets price_snapshot_cents
     *
     * @return int
     */
    public function getPriceSnapshotCents()
    {
        return $this->container['price_snapshot_cents'];
    }

    /**
     * Sets price_snapshot_cents
     *
     * @param int $price_snapshot_cents price_snapshot_cents
     *
     * @return self
     */
    public function setPriceSnapshotCents($price_snapshot_cents)
    {
        if (is_null($price_snapshot_cents)) {
            throw new \InvalidArgumentException('non-nullable price_snapshot_cents cannot be null');
        }
        $this->container['price_snapshot_cents'] = $price_snapshot_cents;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Gemina\Sdk\Model\SubscriptionStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Gemina\Sdk\Model\SubscriptionStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets support_level
     *
     * @return \Gemina\Sdk\Model\SupportLevel
     */
    public function getSupportLevel()
    {
        return $this->container['support_level'];
    }

    /**
     * Sets support_level
     *
     * @param \Gemina\Sdk\Model\SupportLevel $support_level support_level
     *
     * @return self
     */
    public function setSupportLevel($support_level)
    {
        if (is_null($support_level)) {
            throw new \InvalidArgumentException('non-nullable support_level cannot be null');
        }
        $this->container['support_level'] = $support_level;

        return $this;
    }

    /**
     * Gets user_email
     *
     * @return string|null
     */
    public function getUserEmail()
    {
        return $this->container['user_email'];
    }

    /**
     * Sets user_email
     *
     * @param string|null $user_email user_email
     *
     * @return self
     */
    public function setUserEmail($user_email)
    {
        if (is_null($user_email)) {
            throw new \InvalidArgumentException('non-nullable user_email cannot be null');
        }
        $this->container['user_email'] = $user_email;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets webhooks_enabled
     *
     * @return bool
     */
    public function getWebhooksEnabled()
    {
        return $this->container['webhooks_enabled'];
    }

    /**
     * Sets webhooks_enabled
     *
     * @param bool $webhooks_enabled webhooks_enabled
     *
     * @return self
     */
    public function setWebhooksEnabled($webhooks_enabled)
    {
        if (is_null($webhooks_enabled)) {
            throw new \InvalidArgumentException('non-nullable webhooks_enabled cannot be null');
        }
        $this->container['webhooks_enabled'] = $webhooks_enabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


