<?php
/**
 * RetrievalQueryInDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * RetrievalQueryInDTO Class Doc Comment
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RetrievalQueryInDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RetrievalQueryInDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'filters' => '\Gemina\Sdk\Model\RetrievalFiltersDTO',
        'limit' => 'int',
        'mode' => 'string',
        'skip' => 'int',
        'sort_field' => 'string',
        'sort_method' => 'string',
        'text' => 'string',
        'top_k' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'filters' => null,
        'limit' => null,
        'mode' => null,
        'skip' => null,
        'sort_field' => null,
        'sort_method' => null,
        'text' => null,
        'top_k' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'filters' => true,
        'limit' => false,
        'mode' => false,
        'skip' => false,
        'sort_field' => true,
        'sort_method' => false,
        'text' => true,
        'top_k' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'filters' => 'filters',
        'limit' => 'limit',
        'mode' => 'mode',
        'skip' => 'skip',
        'sort_field' => 'sortField',
        'sort_method' => 'sortMethod',
        'text' => 'text',
        'top_k' => 'topK'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'filters' => 'setFilters',
        'limit' => 'setLimit',
        'mode' => 'setMode',
        'skip' => 'setSkip',
        'sort_field' => 'setSortField',
        'sort_method' => 'setSortMethod',
        'text' => 'setText',
        'top_k' => 'setTopK'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'filters' => 'getFilters',
        'limit' => 'getLimit',
        'mode' => 'getMode',
        'skip' => 'getSkip',
        'sort_field' => 'getSortField',
        'sort_method' => 'getSortMethod',
        'text' => 'getText',
        'top_k' => 'getTopK'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const MODE_STRUCTURED = 'structured';
    public const MODE_SEMANTIC = 'semantic';
    public const MODE_HYBRID = 'hybrid';
    public const SORT_FIELD_ISSUE_DATE = 'issue_date';
    public const SORT_FIELD_DUE_DATE = 'due_date';
    public const SORT_FIELD_TOTAL_AMOUNT = 'total_amount';
    public const SORT_FIELD_VENDOR_NAME = 'vendor_name';
    public const SORT_FIELD_CREATED_AT = 'created_at';
    public const SORT_METHOD_ASC = 'asc';
    public const SORT_METHOD_DESC = 'desc';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModeAllowableValues()
    {
        return [
            self::MODE_STRUCTURED,
            self::MODE_SEMANTIC,
            self::MODE_HYBRID,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSortFieldAllowableValues()
    {
        return [
            self::SORT_FIELD_ISSUE_DATE,
            self::SORT_FIELD_DUE_DATE,
            self::SORT_FIELD_TOTAL_AMOUNT,
            self::SORT_FIELD_VENDOR_NAME,
            self::SORT_FIELD_CREATED_AT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSortMethodAllowableValues()
    {
        return [
            self::SORT_METHOD_ASC,
            self::SORT_METHOD_DESC,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('filters', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], 100);
        $this->setIfExists('mode', $data ?? [], 'structured');
        $this->setIfExists('skip', $data ?? [], 0);
        $this->setIfExists('sort_field', $data ?? [], null);
        $this->setIfExists('sort_method', $data ?? [], 'desc');
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('top_k', $data ?? [], 10);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['limit']) && ($this->container['limit'] > 1000)) {
            $invalidProperties[] = "invalid value for 'limit', must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['limit']) && ($this->container['limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'limit', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['skip']) && ($this->container['skip'] < 0)) {
            $invalidProperties[] = "invalid value for 'skip', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getSortFieldAllowableValues();
        if (!is_null($this->container['sort_field']) && !in_array($this->container['sort_field'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sort_field', must be one of '%s'",
                $this->container['sort_field'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSortMethodAllowableValues();
        if (!is_null($this->container['sort_method']) && !in_array($this->container['sort_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sort_method', must be one of '%s'",
                $this->container['sort_method'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['text']) && (mb_strlen($this->container['text']) > 2000)) {
            $invalidProperties[] = "invalid value for 'text', the character length must be smaller than or equal to 2000.";
        }

        if (!is_null($this->container['top_k']) && ($this->container['top_k'] > 100)) {
            $invalidProperties[] = "invalid value for 'top_k', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['top_k']) && ($this->container['top_k'] < 1)) {
            $invalidProperties[] = "invalid value for 'top_k', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets filters
     *
     * @return \Gemina\Sdk\Model\RetrievalFiltersDTO|null
     */
    public function getFilters()
    {
        return $this->container['filters'];
    }

    /**
     * Sets filters
     *
     * @param \Gemina\Sdk\Model\RetrievalFiltersDTO|null $filters filters
     *
     * @return self
     */
    public function setFilters($filters)
    {
        if (is_null($filters)) {
            array_push($this->openAPINullablesSetToNull, 'filters');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filters', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['filters'] = $filters;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit limit
     *
     * @return self
     */
    public function setLimit($limit)
    {
        if (is_null($limit)) {
            throw new \InvalidArgumentException('non-nullable limit cannot be null');
        }

        if (($limit > 1000)) {
            throw new \InvalidArgumentException('invalid value for $limit when calling RetrievalQueryInDTO., must be smaller than or equal to 1000.');
        }
        if (($limit < 1)) {
            throw new \InvalidArgumentException('invalid value for $limit when calling RetrievalQueryInDTO., must be bigger than or equal to 1.');
        }

        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets skip
     *
     * @return int|null
     */
    public function getSkip()
    {
        return $this->container['skip'];
    }

    /**
     * Sets skip
     *
     * @param int|null $skip skip
     *
     * @return self
     */
    public function setSkip($skip)
    {
        if (is_null($skip)) {
            throw new \InvalidArgumentException('non-nullable skip cannot be null');
        }

        if (($skip < 0)) {
            throw new \InvalidArgumentException('invalid value for $skip when calling RetrievalQueryInDTO., must be bigger than or equal to 0.');
        }

        $this->container['skip'] = $skip;

        return $this;
    }

    /**
     * Gets sort_field
     *
     * @return string|null
     */
    public function getSortField()
    {
        return $this->container['sort_field'];
    }

    /**
     * Sets sort_field
     *
     * @param string|null $sort_field sort_field
     *
     * @return self
     */
    public function setSortField($sort_field)
    {
        if (is_null($sort_field)) {
            array_push($this->openAPINullablesSetToNull, 'sort_field');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sort_field', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getSortFieldAllowableValues();
        if (!is_null($sort_field) && !in_array($sort_field, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sort_field', must be one of '%s'",
                    $sort_field,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sort_field'] = $sort_field;

        return $this;
    }

    /**
     * Gets sort_method
     *
     * @return string|null
     */
    public function getSortMethod()
    {
        return $this->container['sort_method'];
    }

    /**
     * Sets sort_method
     *
     * @param string|null $sort_method sort_method
     *
     * @return self
     */
    public function setSortMethod($sort_method)
    {
        if (is_null($sort_method)) {
            throw new \InvalidArgumentException('non-nullable sort_method cannot be null');
        }
        $allowedValues = $this->getSortMethodAllowableValues();
        if (!in_array($sort_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sort_method', must be one of '%s'",
                    $sort_method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sort_method'] = $sort_method;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text Natural-language query (semantic/hybrid modes)
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            array_push($this->openAPINullablesSetToNull, 'text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($text) && (mb_strlen($text) > 2000)) {
            throw new \InvalidArgumentException('invalid length for $text when calling RetrievalQueryInDTO., must be smaller than or equal to 2000.');
        }

        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets top_k
     *
     * @return int|null
     */
    public function getTopK()
    {
        return $this->container['top_k'];
    }

    /**
     * Sets top_k
     *
     * @param int|null $top_k top_k
     *
     * @return self
     */
    public function setTopK($top_k)
    {
        if (is_null($top_k)) {
            throw new \InvalidArgumentException('non-nullable top_k cannot be null');
        }

        if (($top_k > 100)) {
            throw new \InvalidArgumentException('invalid value for $top_k when calling RetrievalQueryInDTO., must be smaller than or equal to 100.');
        }
        if (($top_k < 1)) {
            throw new \InvalidArgumentException('invalid value for $top_k when calling RetrievalQueryInDTO., must be bigger than or equal to 1.');
        }

        $this->container['top_k'] = $top_k;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


